image: gradle:6.8.2-jdk8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


build:
  stage: build
  script:
  - gradle shadowJar
  artifacts:
    paths:
    - build/libs

pages:
  stage: build
  image: gradle:6.8.3-jdk15
  only: master
  script:
  - gradle javadoc
  - mv build/docs/javadoc public
  artifacts:
    paths:
    - public

upload to updater:
  stage: deploy
  only: master
  dependencies:
  - build
  script:
  - cd build/libs
  - files=(*)
  - curl -i -F "submit=true" -F "secret=$UPLOAD_SECRET" -F "file=@${files[0]}" https://ajg0702.us/pl/updater/upload.php

#deploy:
#  image: maven:3.6-jdk-11
#  script:
#    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
#    - mkdir buildtools
#    - cd buildtools
#    - mv ../BuildTools.jar bt.jar
#    - java -jar bt.jar --compile CRAFTBUKKIT
#    - cd CraftBukkit
#   - mvn install
#   - cd ../../
#    - cd ..
#  only:
#    - master
