image: maven:3.3.9-jdk-8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


pages:
  script:
  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  - mkdir buildtools
  - cd buildtools
  - mv ../BuildTools.jar bt.jar
  - java -jar bt.jar
  - mvn javadoc:javadoc
  - ls target
  - mv target/site/apidocs public
  artifacts:
    paths:
    - public

deploy:
  image: maven:3.6-jdk-11
  script:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - mkdir buildtools
    - cd buildtools
    - mv ../BuildTools.jar bt.jar
    - java -jar bt.jar
    - 'mvn deploy -s settings.xml'
  only:
    - master
