image: gradle:6.8.2-jdk8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    - .gradle
    - bin


build:
  script:
  - gradle shadowJar
#  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
#  - mkdir buildtools
#  - cd buildtools
#  - mv ../BuildTools.jar bt.jar 
#  - java -jar bt.jar --compile CRAFTBUKKIT
#  - ls ~/.m2
#  - ls ~/.m2/repository
#  - ls ~/.m2/repository/org
#  - ls ~/.m2/repository/org/bukkit
#  - ls ~/.m2/repository/org/bukkit/craftbukkit/
#  - cd CraftBukkit
#  - mvn install
#  - cd ../../
#  - cd ..
#  - mvn install
#  - 'mvn deploy -s settings.xml'
#  - mvn javadoc:javadoc
#  - ls target
#  - mv target/site/apidocs public
  artifacts:
    paths:
    - public
    - build/libs
#    - target

#deploy:
#  image: maven:3.6-jdk-11
#  script:
#    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
#    - mkdir buildtools
#    - cd buildtools
#    - mv ../BuildTools.jar bt.jar
#    - java -jar bt.jar --compile CRAFTBUKKIT
#    - cd CraftBukkit
#   - mvn install
#   - cd ../../
#    - cd ..    
#  only:
#    - master
